name: Validation
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            runtime:
              - 'src/**'
              - 'frontend/**'
              - 'pom.xml'
              - 'Dockerfile'

      - name: Deploy
        if: ${{ steps.changes.outputs.runtime == 'true' }}
        run: echo deploy

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build application
        run: ./mvnw -ntp -B verify

